name: Publish Prerelease NuGets
on:
  push:
    branches:
      - pre/*
env:
  TIMESTAMP: $(date +'%s')
  SOLUTION: Rougamo.DI.sln
jobs:
  publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Remove Tests
        run: dotnet sln ${{ env.SOLUTION }} remove (ls -r test/**/*.csproj)

      - name: Restore NuGets
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Abstractions Version Setup
        run: |
          $branchName = "${{ github.ref_name }}"
          if (($branchName -ne "pre/abstract") -and ($branchName -notlike "pre/*-full")) {
            $abstractions = @("Rougamo.Extensions.DependencyInjection.Abstractions", "Rougamo.Extensions.DependencyInjection.AspNetCore.Abstractions")
            foreach ($packageName in $abstractions) {
              # 从nuget.org获取最新版本号
              $pattern = "^> $packageName \| (\S+) "
              $packages = nuget search $packageName -PreRelease
              foreach ($pkg in $packages) {
                if ($pkg -match $pattern) {
                  $latestVersion = $matches[1]
                }
              }
              if ($latestVersion -eq $null) {
                $packages = nuget search $packageName
                foreach ($pkg in $packages) {
                  if ($pkg -match $pattern) {
                    $latestVersion = $matches[1]
                  }
                }
              }
              if ($latestVersion -eq $null) {
                throw "Cannot get the latest version of $packageName from nuget.org"
              }
              echo "The latest version of $packageName is $latestVersion"

              # 修改项目文件版本号
              $xmlPath = "src/$packageName/$packageName.csproj"
              [xml]$xmlDoc = Get-Content $xmlPath
              $propertyGroup = $xmlDoc.Project.PropertyGroup
              $versionPrefixNode = $propertyGroup.SelectSingleNode("VersionPrefix")
              $newVersionNode = $xmlDoc.CreateElement("Version")
              $newVersionNode.InnerText = $latestVersion
              $propertyGroup.RemoveChild($versionPrefixNode)
              $propertyGroup.AppendChild($newVersionNode)
              $xmlDoc.Save($xmlPath)
            }
          } else {
            echo "Do not need to setup abstraction projects' version."
          }
        
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore ${{ env.SOLUTION }} --version-suffix preview-${{ env.TIMESTAMP }}

      - name: Delete exists packages
        run: Remove-Item -Path nugets -Recurse -Force -ErrorAction SilentlyContinue

      - name: Pack Solution
        run: dotnet pack ${{ env.SOLUTION }} --configuration Release --no-build --version-suffix preview-${{ env.TIMESTAMP }}

      - name: Publish
        run: |
          $branchName = "${{ github.ref_name }}"
          if ($branchName -like "pre/*-full") {
            # 全量发布先发布公用抽象项目
            $genericHost = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.Abstractions\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $aspnetcore = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.AspNetCore\.Abstractions\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            dotnet nuget push $genericHost.FullName -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json
            dotnet nuget push $aspnetcore.FullName -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json
          }

          if ($branchName -like "pre/microsoft*") {
            $microsoft = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.Microsoft\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $nupkgs = @($microsoft.FullName)
          } elseif ($branchName -like "pre/autofac*") {
            $genericHost = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.Autofac\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $aspnetcore = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.Autofac\.AspNetCore\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $nupkgs = @($genericHost.FullName, $aspnetcore.FullName)
          } elseif ($branchName -eq "pre/abstract") {
            $genericHost = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.Abstractions\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $aspnetcore = Get-ChildItem -Path nugets | Where-Object { $_.Name -match "Rougamo\.Extensions\.DependencyInjection\.AspNetCore\.Abstractions\.\d+\.\d+\.\d+-preview-\d+\.nupkg" }
            $nupkgs = @($genericHost.FullName, $aspnetcore.FullName)
          } else {
            throw "Unknown branch [$branchName]."
          }
          foreach ($nupkg in $nupkgs) {
            dotnet nuget push $nupkg -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json
          }
